### ISSUE TITLE
Leds count incorrect

### ISSUE THREAD

**Issue by uzairali001** [MrBoe/Bambilight#11]
I have got 34 (x2) and 19 (x2) thats makes total of 106 Leds but desktop application is showing 102. I have set 106 Leds in arduino sketch
![capture](https://cloud.githubusercontent.com/assets/10133718/24321767/7b0d0bc4-1176-11e7-940f-dc92bdd46659.PNG)

**Comment by EnForge** [comment]
You don't need to compensate for the spot that your X axis took on each corner.  So each of your corner LED's count for both an X and Y spot.  That's why you're 4 LEDs short on your count.
